### ISSUE TITLE
Mermaid Diagram Not Working With Local Kroki Docker

### ISSUE THREAD

**Issue by 7enderhead** [pomdtr/vscode-markdown-kroki#17]
I am running the latest Kroki docker container locally on Linux.

```
Digest: sha256:cf40792abb2c75c54950523072abb89cccc7fa7f2bbfcb16e262bf159d021374
Status: Downloaded newer image for yuzutech/kroki:latest
docker run -d --name kroki -p 8080:8000 yuzutech/kroki
```

I then configure the plugin to use the local kroki server at "http://localhost:8080".

Diagrams work, but a mermaid diagram seems to want to access a hardcoded (?) port 8002:

~~~
```kroki-mermaid
graph TD
  A[ Anyone ] -->|Can help | B( Go to github.com/yuzutech/kroki )
  B --> C{ How to contribute? }
  C --> D[ Reporting bugs ]
  C --> E[ Sharing ideas ]
  C --> F[ Advocating ]
```
~~~

This is the markdown preview:

![Image](https://github.com/user-attachments/assets/359d56c5-5341-4ed1-a503-9f3c76530774)

**Comment by chiral-faraday** [comment]
Expose the port internally; the main Kroki container takes care of this. Note the `expose` block below. The kroki container is essentially a gateway. If you don't expose it like this then the gateway can't forward the request:

```yaml
services:
  kroki:
    image: yuzutech/kroki
    container_name: kroki_container
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
    tmpfs:
      - /tmp:exec
    networks:
      - krokinet

  mermaid:
    image: yuzutech/kroki-mermaid
    container_name: kroki_mermaid_container
    expose:
      - "8002"
    networks:
      - krokinet
```
